// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adresses.proto

package com.ejemplo.tutorial;

public final class AdresseProto {
  private AdresseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Persona)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string nom = 1;</code>
     */
    boolean hasNom();
    /**
     * <code>required string nom = 1;</code>
     */
    java.lang.String getNom();
    /**
     * <code>required string nom = 1;</code>
     */
    com.google.protobuf.ByteString
        getNomBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string correo = 3;</code>
     */
    boolean hasCorreo();
    /**
     * <code>optional string correo = 3;</code>
     */
    java.lang.String getCorreo();
    /**
     * <code>optional string correo = 3;</code>
     */
    com.google.protobuf.ByteString
        getCorreoBytes();

    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> 
        getTelefonoList();
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono getTelefono(int index);
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    int getTelefonoCount();
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    java.util.List<? extends com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder> 
        getTelefonoOrBuilderList();
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder getTelefonoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Persona}
   *
   * <pre>
   * Numero ilimitado de campos entre ellos int32, float, double o string. 
   * </pre>
   */
  public static final class Persona extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Persona)
      PersonaOrBuilder {
    // Use Persona.newBuilder() to construct.
    private Persona(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Persona(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Persona defaultInstance;
    public static Persona getDefaultInstance() {
      return defaultInstance;
    }

    public Persona getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Persona(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nom_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              correo_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                telefono_ = new java.util.ArrayList<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono>();
                mutable_bitField0_ |= 0x00000008;
              }
              telefono_.add(input.readMessage(com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          telefono_ = java.util.Collections.unmodifiableList(telefono_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ejemplo.tutorial.AdresseProto.Persona.class, com.ejemplo.tutorial.AdresseProto.Persona.Builder.class);
    }

    public static com.google.protobuf.Parser<Persona> PARSER =
        new com.google.protobuf.AbstractParser<Persona>() {
      public Persona parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Persona(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Persona> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.Persona.TipoTelefono}
     */
    public enum TipoTelefono
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CELULAR = 0;</code>
       */
      CELULAR(0, 0),
      /**
       * <code>PERSONAL = 1;</code>
       */
      PERSONAL(1, 1),
      /**
       * <code>PROFESIONAL = 2;</code>
       */
      PROFESIONAL(2, 2),
      ;

      /**
       * <code>CELULAR = 0;</code>
       */
      public static final int CELULAR_VALUE = 0;
      /**
       * <code>PERSONAL = 1;</code>
       */
      public static final int PERSONAL_VALUE = 1;
      /**
       * <code>PROFESIONAL = 2;</code>
       */
      public static final int PROFESIONAL_VALUE = 2;


      public final int getNumber() { return value; }

      public static TipoTelefono valueOf(int value) {
        switch (value) {
          case 0: return CELULAR;
          case 1: return PERSONAL;
          case 2: return PROFESIONAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TipoTelefono>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<TipoTelefono>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TipoTelefono>() {
              public TipoTelefono findValueByNumber(int number) {
                return TipoTelefono.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ejemplo.tutorial.AdresseProto.Persona.getDescriptor().getEnumTypes().get(0);
      }

      private static final TipoTelefono[] VALUES = values();

      public static TipoTelefono valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private TipoTelefono(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Persona.TipoTelefono)
    }

    public interface NumeroTelefonoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tutorial.Persona.NumeroTelefono)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string numero = 1;</code>
       */
      boolean hasNumero();
      /**
       * <code>required string numero = 1;</code>
       */
      java.lang.String getNumero();
      /**
       * <code>required string numero = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumeroBytes();

      /**
       * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
       */
      boolean hasType();
      /**
       * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
       */
      com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono getType();
    }
    /**
     * Protobuf type {@code tutorial.Persona.NumeroTelefono}
     */
    public static final class NumeroTelefono extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:tutorial.Persona.NumeroTelefono)
        NumeroTelefonoOrBuilder {
      // Use NumeroTelefono.newBuilder() to construct.
      private NumeroTelefono(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private NumeroTelefono(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final NumeroTelefono defaultInstance;
      public static NumeroTelefono getDefaultInstance() {
        return defaultInstance;
      }

      public NumeroTelefono getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private NumeroTelefono(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                numero_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono value = com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_NumeroTelefono_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_NumeroTelefono_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.class, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder.class);
      }

      public static com.google.protobuf.Parser<NumeroTelefono> PARSER =
          new com.google.protobuf.AbstractParser<NumeroTelefono>() {
        public NumeroTelefono parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NumeroTelefono(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<NumeroTelefono> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NUMERO_FIELD_NUMBER = 1;
      private java.lang.Object numero_;
      /**
       * <code>required string numero = 1;</code>
       */
      public boolean hasNumero() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string numero = 1;</code>
       */
      public java.lang.String getNumero() {
        java.lang.Object ref = numero_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            numero_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string numero = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumeroBytes() {
        java.lang.Object ref = numero_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numero_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono type_;
      /**
       * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono getType() {
        return type_;
      }

      private void initFields() {
        numero_ = "";
        type_ = com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono.PERSONAL;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNumero()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumeroBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumeroBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.Persona.NumeroTelefono}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tutorial.Persona.NumeroTelefono)
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_NumeroTelefono_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_NumeroTelefono_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.class, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder.class);
        }

        // Construct using com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          numero_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono.PERSONAL;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_NumeroTelefono_descriptor;
        }

        public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono getDefaultInstanceForType() {
          return com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.getDefaultInstance();
        }

        public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono build() {
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono buildPartial() {
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono result = new com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.numero_ = numero_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono) {
            return mergeFrom((com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono other) {
          if (other == com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.getDefaultInstance()) return this;
          if (other.hasNumero()) {
            bitField0_ |= 0x00000001;
            numero_ = other.numero_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumero()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object numero_ = "";
        /**
         * <code>required string numero = 1;</code>
         */
        public boolean hasNumero() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string numero = 1;</code>
         */
        public java.lang.String getNumero() {
          java.lang.Object ref = numero_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              numero_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string numero = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumeroBytes() {
          java.lang.Object ref = numero_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            numero_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string numero = 1;</code>
         */
        public Builder setNumero(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          numero_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string numero = 1;</code>
         */
        public Builder clearNumero() {
          bitField0_ = (bitField0_ & ~0x00000001);
          numero_ = getDefaultInstance().getNumero();
          onChanged();
          return this;
        }
        /**
         * <code>required string numero = 1;</code>
         */
        public Builder setNumeroBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          numero_ = value;
          onChanged();
          return this;
        }

        private com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono type_ = com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono.PERSONAL;
        /**
         * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
         */
        public com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono getType() {
          return type_;
        }
        /**
         * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
         */
        public Builder setType(com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .tutorial.Persona.TipoTelefono type = 2 [default = PERSONAL];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.ejemplo.tutorial.AdresseProto.Persona.TipoTelefono.PERSONAL;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.Persona.NumeroTelefono)
      }

      static {
        defaultInstance = new NumeroTelefono(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tutorial.Persona.NumeroTelefono)
    }

    private int bitField0_;
    public static final int NOM_FIELD_NUMBER = 1;
    private java.lang.Object nom_;
    /**
     * <code>required string nom = 1;</code>
     */
    public boolean hasNom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string nom = 1;</code>
     */
    public java.lang.String getNom() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNomBytes() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CORREO_FIELD_NUMBER = 3;
    private java.lang.Object correo_;
    /**
     * <code>optional string correo = 3;</code>
     */
    public boolean hasCorreo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string correo = 3;</code>
     */
    public java.lang.String getCorreo() {
      java.lang.Object ref = correo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          correo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string correo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCorreoBytes() {
      java.lang.Object ref = correo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONO_FIELD_NUMBER = 4;
    private java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> telefono_;
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> getTelefonoList() {
      return telefono_;
    }
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    public java.util.List<? extends com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder> 
        getTelefonoOrBuilderList() {
      return telefono_;
    }
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    public int getTelefonoCount() {
      return telefono_.size();
    }
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono getTelefono(int index) {
      return telefono_.get(index);
    }
    /**
     * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
     */
    public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder getTelefonoOrBuilder(
        int index) {
      return telefono_.get(index);
    }

    private void initFields() {
      nom_ = "";
      id_ = 0;
      correo_ = "";
      telefono_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTelefonoCount(); i++) {
        if (!getTelefono(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNomBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCorreoBytes());
      }
      for (int i = 0; i < telefono_.size(); i++) {
        output.writeMessage(4, telefono_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNomBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCorreoBytes());
      }
      for (int i = 0; i < telefono_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, telefono_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.Persona parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ejemplo.tutorial.AdresseProto.Persona prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Persona}
     *
     * <pre>
     * Numero ilimitado de campos entre ellos int32, float, double o string. 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Persona)
        com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ejemplo.tutorial.AdresseProto.Persona.class, com.ejemplo.tutorial.AdresseProto.Persona.Builder.class);
      }

      // Construct using com.ejemplo.tutorial.AdresseProto.Persona.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTelefonoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nom_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        correo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (telefonoBuilder_ == null) {
          telefono_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          telefonoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_Persona_descriptor;
      }

      public com.ejemplo.tutorial.AdresseProto.Persona getDefaultInstanceForType() {
        return com.ejemplo.tutorial.AdresseProto.Persona.getDefaultInstance();
      }

      public com.ejemplo.tutorial.AdresseProto.Persona build() {
        com.ejemplo.tutorial.AdresseProto.Persona result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ejemplo.tutorial.AdresseProto.Persona buildPartial() {
        com.ejemplo.tutorial.AdresseProto.Persona result = new com.ejemplo.tutorial.AdresseProto.Persona(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nom_ = nom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.correo_ = correo_;
        if (telefonoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            telefono_ = java.util.Collections.unmodifiableList(telefono_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.telefono_ = telefono_;
        } else {
          result.telefono_ = telefonoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ejemplo.tutorial.AdresseProto.Persona) {
          return mergeFrom((com.ejemplo.tutorial.AdresseProto.Persona)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ejemplo.tutorial.AdresseProto.Persona other) {
        if (other == com.ejemplo.tutorial.AdresseProto.Persona.getDefaultInstance()) return this;
        if (other.hasNom()) {
          bitField0_ |= 0x00000001;
          nom_ = other.nom_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCorreo()) {
          bitField0_ |= 0x00000004;
          correo_ = other.correo_;
          onChanged();
        }
        if (telefonoBuilder_ == null) {
          if (!other.telefono_.isEmpty()) {
            if (telefono_.isEmpty()) {
              telefono_ = other.telefono_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTelefonoIsMutable();
              telefono_.addAll(other.telefono_);
            }
            onChanged();
          }
        } else {
          if (!other.telefono_.isEmpty()) {
            if (telefonoBuilder_.isEmpty()) {
              telefonoBuilder_.dispose();
              telefonoBuilder_ = null;
              telefono_ = other.telefono_;
              bitField0_ = (bitField0_ & ~0x00000008);
              telefonoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTelefonoFieldBuilder() : null;
            } else {
              telefonoBuilder_.addAllMessages(other.telefono_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNom()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getTelefonoCount(); i++) {
          if (!getTelefono(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ejemplo.tutorial.AdresseProto.Persona parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ejemplo.tutorial.AdresseProto.Persona) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nom_ = "";
      /**
       * <code>required string nom = 1;</code>
       */
      public boolean hasNom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string nom = 1;</code>
       */
      public java.lang.String getNom() {
        java.lang.Object ref = nom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nom = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNomBytes() {
        java.lang.Object ref = nom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nom = 1;</code>
       */
      public Builder setNom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nom = 1;</code>
       */
      public Builder clearNom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nom_ = getDefaultInstance().getNom();
        onChanged();
        return this;
      }
      /**
       * <code>required string nom = 1;</code>
       */
      public Builder setNomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nom_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object correo_ = "";
      /**
       * <code>optional string correo = 3;</code>
       */
      public boolean hasCorreo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string correo = 3;</code>
       */
      public java.lang.String getCorreo() {
        java.lang.Object ref = correo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            correo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string correo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCorreoBytes() {
        java.lang.Object ref = correo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string correo = 3;</code>
       */
      public Builder setCorreo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        correo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string correo = 3;</code>
       */
      public Builder clearCorreo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        correo_ = getDefaultInstance().getCorreo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string correo = 3;</code>
       */
      public Builder setCorreoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        correo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> telefono_ =
        java.util.Collections.emptyList();
      private void ensureTelefonoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          telefono_ = new java.util.ArrayList<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono>(telefono_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder> telefonoBuilder_;

      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> getTelefonoList() {
        if (telefonoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(telefono_);
        } else {
          return telefonoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public int getTelefonoCount() {
        if (telefonoBuilder_ == null) {
          return telefono_.size();
        } else {
          return telefonoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono getTelefono(int index) {
        if (telefonoBuilder_ == null) {
          return telefono_.get(index);
        } else {
          return telefonoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder setTelefono(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono value) {
        if (telefonoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonoIsMutable();
          telefono_.set(index, value);
          onChanged();
        } else {
          telefonoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder setTelefono(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder builderForValue) {
        if (telefonoBuilder_ == null) {
          ensureTelefonoIsMutable();
          telefono_.set(index, builderForValue.build());
          onChanged();
        } else {
          telefonoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder addTelefono(com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono value) {
        if (telefonoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonoIsMutable();
          telefono_.add(value);
          onChanged();
        } else {
          telefonoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder addTelefono(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono value) {
        if (telefonoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonoIsMutable();
          telefono_.add(index, value);
          onChanged();
        } else {
          telefonoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder addTelefono(
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder builderForValue) {
        if (telefonoBuilder_ == null) {
          ensureTelefonoIsMutable();
          telefono_.add(builderForValue.build());
          onChanged();
        } else {
          telefonoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder addTelefono(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder builderForValue) {
        if (telefonoBuilder_ == null) {
          ensureTelefonoIsMutable();
          telefono_.add(index, builderForValue.build());
          onChanged();
        } else {
          telefonoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder addAllTelefono(
          java.lang.Iterable<? extends com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono> values) {
        if (telefonoBuilder_ == null) {
          ensureTelefonoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, telefono_);
          onChanged();
        } else {
          telefonoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder clearTelefono() {
        if (telefonoBuilder_ == null) {
          telefono_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          telefonoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public Builder removeTelefono(int index) {
        if (telefonoBuilder_ == null) {
          ensureTelefonoIsMutable();
          telefono_.remove(index);
          onChanged();
        } else {
          telefonoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder getTelefonoBuilder(
          int index) {
        return getTelefonoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder getTelefonoOrBuilder(
          int index) {
        if (telefonoBuilder_ == null) {
          return telefono_.get(index);  } else {
          return telefonoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public java.util.List<? extends com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder> 
           getTelefonoOrBuilderList() {
        if (telefonoBuilder_ != null) {
          return telefonoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(telefono_);
        }
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder addTelefonoBuilder() {
        return getTelefonoFieldBuilder().addBuilder(
            com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder addTelefonoBuilder(
          int index) {
        return getTelefonoFieldBuilder().addBuilder(
            index, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Persona.NumeroTelefono telefono = 4;</code>
       */
      public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder> 
           getTelefonoBuilderList() {
        return getTelefonoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder> 
          getTelefonoFieldBuilder() {
        if (telefonoBuilder_ == null) {
          telefonoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefono.Builder, com.ejemplo.tutorial.AdresseProto.Persona.NumeroTelefonoOrBuilder>(
                  telefono_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          telefono_ = null;
        }
        return telefonoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Persona)
    }

    static {
      defaultInstance = new Persona(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Persona)
  }

  public interface LibretaDireccionesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.LibretaDirecciones)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    java.util.List<com.ejemplo.tutorial.AdresseProto.Persona> 
        getPersonaList();
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    com.ejemplo.tutorial.AdresseProto.Persona getPersona(int index);
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    int getPersonaCount();
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    java.util.List<? extends com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder> 
        getPersonaOrBuilderList();
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder getPersonaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.LibretaDirecciones}
   */
  public static final class LibretaDirecciones extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.LibretaDirecciones)
      LibretaDireccionesOrBuilder {
    // Use LibretaDirecciones.newBuilder() to construct.
    private LibretaDirecciones(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LibretaDirecciones(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LibretaDirecciones defaultInstance;
    public static LibretaDirecciones getDefaultInstance() {
      return defaultInstance;
    }

    public LibretaDirecciones getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LibretaDirecciones(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                persona_ = new java.util.ArrayList<com.ejemplo.tutorial.AdresseProto.Persona>();
                mutable_bitField0_ |= 0x00000001;
              }
              persona_.add(input.readMessage(com.ejemplo.tutorial.AdresseProto.Persona.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          persona_ = java.util.Collections.unmodifiableList(persona_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_LibretaDirecciones_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_LibretaDirecciones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.class, com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.Builder.class);
    }

    public static com.google.protobuf.Parser<LibretaDirecciones> PARSER =
        new com.google.protobuf.AbstractParser<LibretaDirecciones>() {
      public LibretaDirecciones parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LibretaDirecciones(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LibretaDirecciones> getParserForType() {
      return PARSER;
    }

    public static final int PERSONA_FIELD_NUMBER = 1;
    private java.util.List<com.ejemplo.tutorial.AdresseProto.Persona> persona_;
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona> getPersonaList() {
      return persona_;
    }
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    public java.util.List<? extends com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder> 
        getPersonaOrBuilderList() {
      return persona_;
    }
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    public int getPersonaCount() {
      return persona_.size();
    }
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    public com.ejemplo.tutorial.AdresseProto.Persona getPersona(int index) {
      return persona_.get(index);
    }
    /**
     * <code>repeated .tutorial.Persona persona = 1;</code>
     */
    public com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder getPersonaOrBuilder(
        int index) {
      return persona_.get(index);
    }

    private void initFields() {
      persona_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPersonaCount(); i++) {
        if (!getPersona(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < persona_.size(); i++) {
        output.writeMessage(1, persona_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < persona_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, persona_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ejemplo.tutorial.AdresseProto.LibretaDirecciones prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.LibretaDirecciones}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.LibretaDirecciones)
        com.ejemplo.tutorial.AdresseProto.LibretaDireccionesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_LibretaDirecciones_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_LibretaDirecciones_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.class, com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.Builder.class);
      }

      // Construct using com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonaFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personaBuilder_ == null) {
          persona_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personaBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ejemplo.tutorial.AdresseProto.internal_static_tutorial_LibretaDirecciones_descriptor;
      }

      public com.ejemplo.tutorial.AdresseProto.LibretaDirecciones getDefaultInstanceForType() {
        return com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.getDefaultInstance();
      }

      public com.ejemplo.tutorial.AdresseProto.LibretaDirecciones build() {
        com.ejemplo.tutorial.AdresseProto.LibretaDirecciones result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ejemplo.tutorial.AdresseProto.LibretaDirecciones buildPartial() {
        com.ejemplo.tutorial.AdresseProto.LibretaDirecciones result = new com.ejemplo.tutorial.AdresseProto.LibretaDirecciones(this);
        int from_bitField0_ = bitField0_;
        if (personaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            persona_ = java.util.Collections.unmodifiableList(persona_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.persona_ = persona_;
        } else {
          result.persona_ = personaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ejemplo.tutorial.AdresseProto.LibretaDirecciones) {
          return mergeFrom((com.ejemplo.tutorial.AdresseProto.LibretaDirecciones)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ejemplo.tutorial.AdresseProto.LibretaDirecciones other) {
        if (other == com.ejemplo.tutorial.AdresseProto.LibretaDirecciones.getDefaultInstance()) return this;
        if (personaBuilder_ == null) {
          if (!other.persona_.isEmpty()) {
            if (persona_.isEmpty()) {
              persona_ = other.persona_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonaIsMutable();
              persona_.addAll(other.persona_);
            }
            onChanged();
          }
        } else {
          if (!other.persona_.isEmpty()) {
            if (personaBuilder_.isEmpty()) {
              personaBuilder_.dispose();
              personaBuilder_ = null;
              persona_ = other.persona_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personaBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonaFieldBuilder() : null;
            } else {
              personaBuilder_.addAllMessages(other.persona_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonaCount(); i++) {
          if (!getPersona(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ejemplo.tutorial.AdresseProto.LibretaDirecciones parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ejemplo.tutorial.AdresseProto.LibretaDirecciones) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ejemplo.tutorial.AdresseProto.Persona> persona_ =
        java.util.Collections.emptyList();
      private void ensurePersonaIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          persona_ = new java.util.ArrayList<com.ejemplo.tutorial.AdresseProto.Persona>(persona_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ejemplo.tutorial.AdresseProto.Persona, com.ejemplo.tutorial.AdresseProto.Persona.Builder, com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder> personaBuilder_;

      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona> getPersonaList() {
        if (personaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(persona_);
        } else {
          return personaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public int getPersonaCount() {
        if (personaBuilder_ == null) {
          return persona_.size();
        } else {
          return personaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona getPersona(int index) {
        if (personaBuilder_ == null) {
          return persona_.get(index);
        } else {
          return personaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder setPersona(
          int index, com.ejemplo.tutorial.AdresseProto.Persona value) {
        if (personaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonaIsMutable();
          persona_.set(index, value);
          onChanged();
        } else {
          personaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder setPersona(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.Builder builderForValue) {
        if (personaBuilder_ == null) {
          ensurePersonaIsMutable();
          persona_.set(index, builderForValue.build());
          onChanged();
        } else {
          personaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder addPersona(com.ejemplo.tutorial.AdresseProto.Persona value) {
        if (personaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonaIsMutable();
          persona_.add(value);
          onChanged();
        } else {
          personaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder addPersona(
          int index, com.ejemplo.tutorial.AdresseProto.Persona value) {
        if (personaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonaIsMutable();
          persona_.add(index, value);
          onChanged();
        } else {
          personaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder addPersona(
          com.ejemplo.tutorial.AdresseProto.Persona.Builder builderForValue) {
        if (personaBuilder_ == null) {
          ensurePersonaIsMutable();
          persona_.add(builderForValue.build());
          onChanged();
        } else {
          personaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder addPersona(
          int index, com.ejemplo.tutorial.AdresseProto.Persona.Builder builderForValue) {
        if (personaBuilder_ == null) {
          ensurePersonaIsMutable();
          persona_.add(index, builderForValue.build());
          onChanged();
        } else {
          personaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder addAllPersona(
          java.lang.Iterable<? extends com.ejemplo.tutorial.AdresseProto.Persona> values) {
        if (personaBuilder_ == null) {
          ensurePersonaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, persona_);
          onChanged();
        } else {
          personaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder clearPersona() {
        if (personaBuilder_ == null) {
          persona_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public Builder removePersona(int index) {
        if (personaBuilder_ == null) {
          ensurePersonaIsMutable();
          persona_.remove(index);
          onChanged();
        } else {
          personaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.Builder getPersonaBuilder(
          int index) {
        return getPersonaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder getPersonaOrBuilder(
          int index) {
        if (personaBuilder_ == null) {
          return persona_.get(index);  } else {
          return personaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public java.util.List<? extends com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder> 
           getPersonaOrBuilderList() {
        if (personaBuilder_ != null) {
          return personaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(persona_);
        }
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.Builder addPersonaBuilder() {
        return getPersonaFieldBuilder().addBuilder(
            com.ejemplo.tutorial.AdresseProto.Persona.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public com.ejemplo.tutorial.AdresseProto.Persona.Builder addPersonaBuilder(
          int index) {
        return getPersonaFieldBuilder().addBuilder(
            index, com.ejemplo.tutorial.AdresseProto.Persona.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Persona persona = 1;</code>
       */
      public java.util.List<com.ejemplo.tutorial.AdresseProto.Persona.Builder> 
           getPersonaBuilderList() {
        return getPersonaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ejemplo.tutorial.AdresseProto.Persona, com.ejemplo.tutorial.AdresseProto.Persona.Builder, com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder> 
          getPersonaFieldBuilder() {
        if (personaBuilder_ == null) {
          personaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ejemplo.tutorial.AdresseProto.Persona, com.ejemplo.tutorial.AdresseProto.Persona.Builder, com.ejemplo.tutorial.AdresseProto.PersonaOrBuilder>(
                  persona_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          persona_ = null;
        }
        return personaBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.LibretaDirecciones)
    }

    static {
      defaultInstance = new LibretaDirecciones(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.LibretaDirecciones)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Persona_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Persona_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Persona_NumeroTelefono_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Persona_NumeroTelefono_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_LibretaDirecciones_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_LibretaDirecciones_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016adresses.proto\022\010tutorial\"\374\001\n\007Persona\022\013" +
      "\n\003nom\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\016\n\006correo\030\003 \001(\t\022" +
      "2\n\010telefono\030\004 \003(\0132 .tutorial.Persona.Num" +
      "eroTelefono\032X\n\016NumeroTelefono\022\016\n\006numero\030" +
      "\001 \002(\t\0226\n\004type\030\002 \001(\0162\036.tutorial.Persona.T" +
      "ipoTelefono:\010PERSONAL\":\n\014TipoTelefono\022\013\n" +
      "\007CELULAR\020\000\022\014\n\010PERSONAL\020\001\022\017\n\013PROFESIONAL\020" +
      "\002\"8\n\022LibretaDirecciones\022\"\n\007persona\030\001 \003(\013" +
      "2\021.tutorial.PersonaB$\n\024com.ejemplo.tutor" +
      "ialB\014AdresseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Persona_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Persona_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Persona_descriptor,
        new java.lang.String[] { "Nom", "Id", "Correo", "Telefono", });
    internal_static_tutorial_Persona_NumeroTelefono_descriptor =
      internal_static_tutorial_Persona_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_Persona_NumeroTelefono_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Persona_NumeroTelefono_descriptor,
        new java.lang.String[] { "Numero", "Type", });
    internal_static_tutorial_LibretaDirecciones_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_LibretaDirecciones_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_LibretaDirecciones_descriptor,
        new java.lang.String[] { "Persona", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
